In [93]:
import pandas as pd
from sqlalchemy import create_engine

## Storing CSV as Panda Dataframe

In [94]:
csv_file = "Resources/businesses.csv"
customer_data_df = pd.read_csv(csv_file, encoding="ISO-8859-1")
#customer_data_df = pd.read_csv(csv_file, encoding="utf-8")
customer_data_df

,business_id,name,address,city,state,postal_code,latitude,longitude,phone_number
0,PR0000206,JOSYLN SENIOR CENTER,210 N CHAPEL AVE,ALHAMBRA,CA,91801,34.098526,-118.124767,626-960-2995
1,PR0000213,STARBUCKS COFFEE #9685,145 N CITRUS AVE,COVINA,CA,91723,34.087327,-117.890460,NaN
2,PR0000250,VFW POST NO. 6110,16555 SIERRA HWY,CANYON COUNTRY,CA,91351-1338,34.447567,-118.426207,661-252-9989
3,PR0000273,STABUCKS @ VONS #2066,18439 VENTURA BLVD,TARZANA,CA,91356,34.168381,-118.534570,NaN
4,PR0000278,COCOHODO TORRANCE,2734 SEPULVEDA BLVD,TORRANCE,CA,90505,33.822488,-118.333178,310-530-3875
5,PR0000307,KING'S BAKERY,127 N GARFIELD AVE STE J,MONTEREY PARK,CA,91754,34.063328,-118.123686,NaN
6,PR0000335,4 SEASONS HOTEL-THE BAR,2 DOLE DR,WESTLAKE VILLAGE,CA,91362,34.151368,-118.804506,NaN
7,PR0000462,TERRACE CINEMAS 6,28901 S WESTERN AVE,RANCHO PALOS VERDES,CA,90275,33.756354,-118.310398,310-831-1919
8,PR0000527,VONS-STARBUCKS #1638,4226 WOODRUFF AVE,LAKEWOOD,CA,90713,33.835175,-118.115432,NaN
9,PR0000572,BASKIN ROBBINS,6700 LAUREL CANYON BLVD,NORTH HOLLYWOOD,CA,91606,34.192320,-118.396314,NaN
10,PR0000592,STARBUCKS COFFEE #5348,2100 S ATLANTIC BLVD,MONTEREY PARK,CA,91754,34.038347,-118.144500,NaN
11,PR0000665,VONS STARBUCKS #2001,5671 KANAN RD,AGOURA HILLS,CA,91301,34.153399,-118.757543,NaN
12,PR0000848,ICEE MIX IT UP,111 RAGING WATERS DR,SAN DIMAS,CA,91773-3928,34.095563,-117.810014,NaN
13,PR0000870,LAS TORRES,11717 1/2 VICTORY BLVD,NORTH HOLLYWOOD,CA,91606,34.186828,-118.388376,NaN
14,PR0000907,EARTH BAR EQUINOX ENCINO,16830 VENTURA BLVD # #165,ENCINO,CA,91436,34.158914,-118.499787,310-717-9002
15,PR0001079,BAR 20-CLUBHOUSE,285 W HUNTINGTON DR,ARCADIA,CA,91007,34.139713,-118.045304,NaN
16,PR0001109,ST. BARNABAS SENIOR CENTER OF LA,675 S CARONDELET ST,LOS ANGELES,CA,90057,34.059267,-118.281234,213-388-4444
17,PR0001112,COFFEE BEAN & TEA LEAF,6600 TOPANGA CANYON BLVD UNIT 9220,CANOGA PARK,CA,91303,34.190077,-118.604267,NaN
18,PR0001205,SIERRA MADRE PARK (HEASLEY),611 E SIERRA MADRE BLVD,SIERRA MADRE,CA,91024,34.164538,-118.039978,626-355-5293
19,PR0001207,STARBUCKS COFFEE #2989,11809 ARTESIA BLVD,ARTESIA,CA,90701,33.874195,-118.081907,NaN
20,PR0001209,COCO FRESH TEA & JUICE,11301 W OLYMPIC BLVD STE 105,LOS ANGELES,CA,90064,34.038185,-118.441811,626-319-5570
21,PR0001212,BOTTOM LINE,2066 W MANCHESTER AVE,LOS ANGELES,CA,90047,33.959802,-118.315636,NaN
22,PR0001240,BM-TRY WASHING ROOM,735 E 12TH ST # 415,LOS ANGELES,CA,90021,34.033246,-118.252307,213-746-6633
23,PR0001350,STARBUCKS #13222,800 W OLYMPIC BLVD STE 102,LOS ANGELES,CA,90015,34.044838,-118.264527,213-748-1009
24,PR0001391,STARBUCKS COFFEE CO,131 S BARRINGTON AVE,LOS ANGELES,CA,90049,34.066396,-118.469330,NaN
25,PR0001417,RAJI'S,5851 W SUNSET BLVD,LOS ANGELES,CA,90028,34.098214,-118.317469,NaN
26,PR0001609,STUB HUB CENTER ACE'S COURT #17,18400 AVALON BLVD STE 300,CARSON,CA,90746-2182,33.866014,-118.264740,NaN
27,PR0001669,TARGET STORES #222 - STARBUCKS,17751 E COLIMA RD,INDUSTRY,CA,91748,33.991562,-117.918644,NaN
28,PR0001671,TIKI TI,4427 W SUNSET BLVD,LOS ANGELES,CA,90027,34.097470,-118.285736,NaN
29,PR0001688,REGAL ENTERTAINMENT GROUP,1919 W VERDUGO BLVD,LA CANADA FLINTRIDGE,CA,91011,34.206546,-118.217001,NaN
...,...,...,...,...,...,...,...,...,...
29253,PR0218903,IHOP 3583,4410 W CENTURY BLVD,INGLEWOOD,CA,90304,33.945413,-118.353474,310-844-7196
29254,PR0218994,RIO PICANHA STEAKHOUSE,381 N AZUSA AVE,WEST COVINA,CA,91791,34.077142,-117.907860,213-248-2550
29255,PR0219006,MR FURLEY'S BAR,224 N BRAND BLVD # 1006,GLENDALE,CA,91203,34.149060,-118.254921,NaN
29256,PR0219024,UNITED AIRLINES POLARIS LOUNGE,700 WORLD WAY,LOS ANGELES,CA,90045,33.943049,-118.401070,NaN
29257,PR0219170,OUTBACK STEAKHOUSE,18711 DEVONSHIRE ST,NORTHRIDGE,CA,91324,34.257295,-118.540503,858-456-2703
29258,PR0219214,MAIN KITCHEN - 2ND FLR,3900 W MANCHESTER BLVD,INGLEWOOD,CA,90305,33.959889,-118.343638,716-858-5216
29259,PR0219270,AURORA BANQUET HALL,7179 FOOTHILL BLVD,TUJUNGA,CA,91042-2716,34.248590,-118.288488,818-352-7748
29260,PR0219291,PANDA INN #2,201 N MARYLAND AVE,GLENDALE,CA,91206,34.148157,-118.253848,NaN
29261,PR0219786,STANLEY'S CAFE,21255 CALIFA ST,WOODLAND HILLS,CA,91367,34.177163,-118.594839,818-713-1000
29262,PR0219792,THE GRILLE AT DEBELL,1500 E WALNUT AVE,BURBANK,CA,91501,34.209140,-118.304470,818-845-0022
29263,PR0219832,ELU BANQUET HALL,6330 LAUREL CANYON BLVD,NORTH HOLLYWOOD,CA,91606,34.185745,-118.396498,323-387-2470
29264,PR0220248,LUXY KARAOKE LOUNGE & BAR RESTAURANT,400 S BALDWIN AVE # 2225,ARCADIA,CA,91007,34.135337,-118.051514,626-348-8156
29265,PR0220414,BROKEN RICE,1612 MONTEBELLO TOWN CENTER DR,MONTEBELLO,CA,90640,34.036839,-118.087001,NaN
29266,PR0220532,OUTBACK STEAKHOUSE,5305 CLARK AVE,LAKEWOOD,CA,90712,33.853977,-118.133826,858-456-2703
29267,PR0220713,LA FERIA RESTAURANT,1903 INGLEWOOD AVE,INGLEWOOD,CA,90304,33.913579,-118.361290,310-673-7475
29268,PR0220955,HOPE CAFE & CATERING,111 N HOPE ST,LOS ANGELES,CA,90012,34.056848,-118.249464,310-871-6679
29269,PR0221194,EL TORITO CANTINA AUTENTICA,8855 TAMPA AVE,NORTHRIDGE,CA,91324,34.231428,-118.553586,818-349-1607
29270,PR0221357,SEOUL JUNG,900 WILSHIRE BLVD STE 212,LOS ANGELES,CA,90017-4701,34.050152,-118.259476,NaN
29271,PR0221566,EMC SEAFOOD AND RAW BAR,21536 HAWTHORNE BLVD,TORRANCE,CA,90503,33.832680,-118.352664,NaN
29272,PR0221687,6TH KITCHEN,1717 N VINE ST,LOS ANGELES,CA,90028,34.102687,-118.326747,323-962-1717
29273,PR0221693,5TH FLOOR KITCHEN,1717 N VINE ST,LOS ANGELES,CA,90028,34.102687,-118.326747,323-962-1717
29274,PR0221727,CASA CAMINO FIFI,9060 SLAUSON AVE,PICO RIVERA,CA,90660,33.970343,-118.103409,562-463-3505
29275,PR0221795,DIVINE FOOD & CATERING,1219 VINE ST,LOS ANGELES,CA,90038,34.093026,-118.326655,NaN
29276,PR0221800,DEL FRISCO'S DOUBLE EAGLE STEAKHOUSE,10250 SANTA MONICA BLVD # 1700,LOS ANGELES,CA,90067,34.060036,-118.419887,NaN
29277,PR0221826,GOLDEN PAGODA,950 MEI LING WAY,LOS ANGELES,CA,90012,34.065164,-118.237906,213-600-4188
29278,PR0221849,CARSON BUFFET,888 DOMINGUEZ ST,CARSON,CA,90746,33.840453,-118.260287,310-324-3688
29279,PR0221862,THE RAVEN'S NEST,42458 60TH ST W # 103,LANCASTER,CA,93536,34.654913,-118.236206,661-209-7514
29280,PR0222387,RH BBQ,18311 COLIMA RD # A,ROWLAND HEIGHTS,CA,90640,33.988545,-117.905523,626-964-9595
29281,PR0222552,CHESS PARK TAVERN,231 N BRAND BLVD,GLENDALE,CA,91203,34.148999,-118.255146,NaN
29282,PR0222568,MOA BAR,865 S VERMONT AVE,LOS ANGELES,CA,90005-1522,34.056155,-118.291688,213-378-0050

## Create new data with select columns

In [95]:
new_customer_data_df = customer_data_df[['business_id', 'name', 'address','city','state','postal_code' ]].copy()
new_customer_data_df

,business_id,name,address,city,state,postal_code
0,PR0000206,JOSYLN SENIOR CENTER,210 N CHAPEL AVE,ALHAMBRA,CA,91801
1,PR0000213,STARBUCKS COFFEE #9685,145 N CITRUS AVE,COVINA,CA,91723
2,PR0000250,VFW POST NO. 6110,16555 SIERRA HWY,CANYON COUNTRY,CA,91351-1338
3,PR0000273,STABUCKS @ VONS #2066,18439 VENTURA BLVD,TARZANA,CA,91356
4,PR0000278,COCOHODO TORRANCE,2734 SEPULVEDA BLVD,TORRANCE,CA,90505
5,PR0000307,KING'S BAKERY,127 N GARFIELD AVE STE J,MONTEREY PARK,CA,91754
6,PR0000335,4 SEASONS HOTEL-THE BAR,2 DOLE DR,WESTLAKE VILLAGE,CA,91362
7,PR0000462,TERRACE CINEMAS 6,28901 S WESTERN AVE,RANCHO PALOS VERDES,CA,90275
8,PR0000527,VONS-STARBUCKS #1638,4226 WOODRUFF AVE,LAKEWOOD,CA,90713
9,PR0000572,BASKIN ROBBINS,6700 LAUREL CANYON BLVD,NORTH HOLLYWOOD,CA,91606
10,PR0000592,STARBUCKS COFFEE #5348,2100 S ATLANTIC BLVD,MONTEREY PARK,CA,91754
11,PR0000665,VONS STARBUCKS #2001,5671 KANAN RD,AGOURA HILLS,CA,91301
12,PR0000848,ICEE MIX IT UP,111 RAGING WATERS DR,SAN DIMAS,CA,91773-3928
13,PR0000870,LAS TORRES,11717 1/2 VICTORY BLVD,NORTH HOLLYWOOD,CA,91606
14,PR0000907,EARTH BAR EQUINOX ENCINO,16830 VENTURA BLVD # #165,ENCINO,CA,91436
15,PR0001079,BAR 20-CLUBHOUSE,285 W HUNTINGTON DR,ARCADIA,CA,91007
16,PR0001109,ST. BARNABAS SENIOR CENTER OF LA,675 S CARONDELET ST,LOS ANGELES,CA,90057
17,PR0001112,COFFEE BEAN & TEA LEAF,6600 TOPANGA CANYON BLVD UNIT 9220,CANOGA PARK,CA,91303
18,PR0001205,SIERRA MADRE PARK (HEASLEY),611 E SIERRA MADRE BLVD,SIERRA MADRE,CA,91024
19,PR0001207,STARBUCKS COFFEE #2989,11809 ARTESIA BLVD,ARTESIA,CA,90701
20,PR0001209,COCO FRESH TEA & JUICE,11301 W OLYMPIC BLVD STE 105,LOS ANGELES,CA,90064
21,PR0001212,BOTTOM LINE,2066 W MANCHESTER AVE,LOS ANGELES,CA,90047
22,PR0001240,BM-TRY WASHING ROOM,735 E 12TH ST # 415,LOS ANGELES,CA,90021
23,PR0001350,STARBUCKS #13222,800 W OLYMPIC BLVD STE 102,LOS ANGELES,CA,90015
24,PR0001391,STARBUCKS COFFEE CO,131 S BARRINGTON AVE,LOS ANGELES,CA,90049
25,PR0001417,RAJI'S,5851 W SUNSET BLVD,LOS ANGELES,CA,90028
26,PR0001609,STUB HUB CENTER ACE'S COURT #17,18400 AVALON BLVD STE 300,CARSON,CA,90746-2182
27,PR0001669,TARGET STORES #222 - STARBUCKS,17751 E COLIMA RD,INDUSTRY,CA,91748
28,PR0001671,TIKI TI,4427 W SUNSET BLVD,LOS ANGELES,CA,90027
29,PR0001688,REGAL ENTERTAINMENT GROUP,1919 W VERDUGO BLVD,LA CANADA FLINTRIDGE,CA,91011
...,...,...,...,...,...,...
29253,PR0218903,IHOP 3583,4410 W CENTURY BLVD,INGLEWOOD,CA,90304
29254,PR0218994,RIO PICANHA STEAKHOUSE,381 N AZUSA AVE,WEST COVINA,CA,91791
29255,PR0219006,MR FURLEY'S BAR,224 N BRAND BLVD # 1006,GLENDALE,CA,91203
29256,PR0219024,UNITED AIRLINES POLARIS LOUNGE,700 WORLD WAY,LOS ANGELES,CA,90045
29257,PR0219170,OUTBACK STEAKHOUSE,18711 DEVONSHIRE ST,NORTHRIDGE,CA,91324
29258,PR0219214,MAIN KITCHEN - 2ND FLR,3900 W MANCHESTER BLVD,INGLEWOOD,CA,90305
29259,PR0219270,AURORA BANQUET HALL,7179 FOOTHILL BLVD,TUJUNGA,CA,91042-2716
29260,PR0219291,PANDA INN #2,201 N MARYLAND AVE,GLENDALE,CA,91206
29261,PR0219786,STANLEY'S CAFE,21255 CALIFA ST,WOODLAND HILLS,CA,91367
29262,PR0219792,THE GRILLE AT DEBELL,1500 E WALNUT AVE,BURBANK,CA,91501
29263,PR0219832,ELU BANQUET HALL,6330 LAUREL CANYON BLVD,NORTH HOLLYWOOD,CA,91606
29264,PR0220248,LUXY KARAOKE LOUNGE & BAR RESTAURANT,400 S BALDWIN AVE # 2225,ARCADIA,CA,91007
29265,PR0220414,BROKEN RICE,1612 MONTEBELLO TOWN CENTER DR,MONTEBELLO,CA,90640
29266,PR0220532,OUTBACK STEAKHOUSE,5305 CLARK AVE,LAKEWOOD,CA,90712
29267,PR0220713,LA FERIA RESTAURANT,1903 INGLEWOOD AVE,INGLEWOOD,CA,90304
29268,PR0220955,HOPE CAFE & CATERING,111 N HOPE ST,LOS ANGELES,CA,90012
29269,PR0221194,EL TORITO CANTINA AUTENTICA,8855 TAMPA AVE,NORTHRIDGE,CA,91324
29270,PR0221357,SEOUL JUNG,900 WILSHIRE BLVD STE 212,LOS ANGELES,CA,90017-4701
29271,PR0221566,EMC SEAFOOD AND RAW BAR,21536 HAWTHORNE BLVD,TORRANCE,CA,90503
29272,PR0221687,6TH KITCHEN,1717 N VINE ST,LOS ANGELES,CA,90028
29273,PR0221693,5TH FLOOR KITCHEN,1717 N VINE ST,LOS ANGELES,CA,90028
29274,PR0221727,CASA CAMINO FIFI,9060 SLAUSON AVE,PICO RIVERA,CA,90660
29275,PR0221795,DIVINE FOOD & CATERING,1219 VINE ST,LOS ANGELES,CA,90038
29276,PR0221800,DEL FRISCO'S DOUBLE EAGLE STEAKHOUSE,10250 SANTA MONICA BLVD # 1700,LOS ANGELES,CA,90067
29277,PR0221826,GOLDEN PAGODA,950 MEI LING WAY,LOS ANGELES,CA,90012
29278,PR0221849,CARSON BUFFET,888 DOMINGUEZ ST,CARSON,CA,90746
29279,PR0221862,THE RAVEN'S NEST,42458 60TH ST W # 103,LANCASTER,CA,93536
29280,PR0222387,RH BBQ,18311 COLIMA RD # A,ROWLAND HEIGHTS,CA,90640
29281,PR0222552,CHESS PARK TAVERN,231 N BRAND BLVD,GLENDALE,CA,91203
29282,PR0222568,MOA BAR,865 S VERMONT AVE,LOS ANGELES,CA,90005-1522

## Storing JSON file as Dataframe

In [96]:
json_file = "Resources/inspection.json"
inspection= pd.read_json(json_file, orient='records')
inspection

       business_id      date description  score     type
0        PR0014182  20170207                 95  Routine
1        PR0005730  20161216                 99  Routine
2        PR0003877  20170105                 96  Routine
3        PR0014471  20180921                 98  Routine
4        PR0003383  20170818                 99  Routine
5        PR0002000  20161220                100  Routine
6        PR0019930  20170201                 99  Routine
7        PR0010463  20161103                 98  Routine
8        PR0019356  20170309                100  Routine
9        PR0005769  20170309                 92  Routine
10       PR0010538  20170310                 91  Routine
11       PR0011153  20170503                 93  Routine
12       PR0005118  20170515                 95  Routine
13       PR0005769  20170623                 99  Routine
14       PR0003830  20170830                100  Routine
15       PR0002310  20180906                 94  Routine
16       PR0013036  20181116                 97  Routine
17       PR0002857  20190222                 98  Routine
18       PR0021763  20170428                 99  Routine
19       PR0015942  20170125                 96  Routine
20       PR0013627  20180410                 94  Routine
21       PR0004434  20171213                 97  Routine
22       PR0017472  20181101                 97  Routine
23       PR0003152  20180607                 96  Routine
24       PR0014985  20181018                 98  Routine
25       PR0019029  20171211                 97  Routine
26       PR0013890  20161012                 99  Routine
27       PR0012355  20180717                 94  Routine
28       PR0005790  20181130                 92  Routine
29       PR0003484  20170517                 93  Routine
...            ...       ...         ...    ...      ...
143719   PR0190705  20180309                 97  Routine
143720   PR0201610  20190213                 90  Routine
143721   PR0212921  20180726                 95  Routine
143722   PR0201914  20190130                 91  Routine
143723   PR0192590  20181102                 93  Routine
143724   PR0190066  20180514                 92  Routine
143725   PR0189785  20181016                 90  Routine
143726   PR0220396  20190129                 99  Routine
143727   PR0193247  20171214                 95  Routine
143728   PR0214516  20181206                 91  Routine
143729   PR0191417  20170217                 96  Routine
143730   PR0207183  20180315                 96  Routine
143731   PR0216312  20181126                 95  Routine
143732   PR0194297  20180206                 96  Routine
143733   PR0194085  20170519                 92  Routine
143734   PR0198133  20180723                 94  Routine
143735   PR0193485  20171030                 97  Routine
143736   PR0197823  20170905                 90  Routine
143737   PR0190545  20170105                 93  Routine
143738   PR0198416  20170915                 94  Routine
143739   PR0194194  20180117                 96  Routine
143740   PR0192902  20171102                 97  Routine
143741   PR0193303  20180808                 95  Routine
143742   PR0214517  20190129                 80  Routine
143743   PR0200679  20180302                 94  Routine
143744   PR0193493  20170915                 99  Routine
143745   PR0200284  20171228                 84  Routine
143746   PR0199529  20170914                 97  Routine
143747   PR0191379  20170418                100  Routine
143748   PR0190613  20181016                 95  Routine

[143749 rows x 5 columns]

## Cleaning Dataframe

In [97]:
df = inspection[["business_id","date", "score"]].copy()
df.head()

  business_id      date  score
0   PR0014182  20170207     95
1   PR0005730  20161216     99
2   PR0003877  20170105     96
3   PR0014471  20180921     98
4   PR0003383  20170818     99

In [98]:
#out=clean_df.to_json(orient='records', lines=True)
#with open('new3_business.json', 'w') as f:
#    f.write(out)

## Connecting to local database

In [99]:
## Are we using SQL or MONGODB. IF SQL, we can use this

In [100]:
rds_connection_string = "root:Dt*A4rNe@localhost/yelp_inspection_db"
engine = create_engine(f'mysql+pymysql://{rds_connection_string}')

In [101]:
engine.table_names()

['businesses', 'inspection']

In [102]:
new_customer_data_df.to_sql(name='businesses', con=engine, if_exists='append', index=False)

In [103]:
df.to_sql(name='inspection', con=engine, if_exists='append', index=False)

In [104]:
pd.read_sql_query('select * from businesses', con=engine).head()

,business_id,name,address,city,state,postal_code
0,PR0000002,GLADSTONE'S OUTSIDE KITCHEN,17300 PACIFIC COAST HWY,PACIFIC PALISADES,CA,90272
1,PR0000004,TERRANEA - MAIN KITCHEN,100 TERRANEA WAY,RANCHO PALOS VERDES,CA,90275-1013
2,PR0000005,CHIPOTLE MEXICAN GRILL,11690 W SAN VICENTE BLVD,LOS ANGELES,CA,90049
3,PR0000011,TACOS PUEBLA,14223 BELLFLOWER BLVD,BELLFLOWER,CA,90706
4,PR0000012,MARMALADE CAFE,6333 W 3RD ST E #E-17,LOS ANGELES,CA,90036

In [107]:
pd.read_sql_query('select * from inspection', con=engine).head()

   inspection_id business_id      date score
0              1   PR0014182  20170207    95
1              2   PR0005730  20161216    99
2              3   PR0003877  20170105    96
3              4   PR0014471  20180921    98
4              5   PR0003383  20170818    99

In [109]:
pd.read_sql_query('SELECT businesses.business_id, businesses.name, businesses.city, inspection.score, inspection.date FROM businesses INNER JOIN inspection ON businesses.business_id = inspection.business_id;', con=engine).head()

,business_id,name,city,score,date
0,PR0014182,ROCKY MOUNTAIN CHOCOLATE,WEST COVINA,95,20170207
1,PR0005730,CENTURY THEATER,NORTH HOLLYWOOD,99,20161216
2,PR0003877,AMC CAFE,WOODLAND HILLS,96,20170105
3,PR0014471,MARINA DEL REY MARRIOTT - HOTEL BAR,MARINA DEL REY,98,20180921
4,PR0003383,STARBUCKS COFFEE #643,ENCINO,99,20170818